version: '3'
services:
  rabbitmq:
    image: "rabbitmq:3.10-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - MyNetwork  

  generator:
    build:
      context: ./dataGeneration/
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_HOST: rabbitmq
    volumes:
      - ./dataGeneration:/generation
    networks:
      - MyNetwork  
  
  analyzer:
      build:
        context: ./dataAnalyzer/
      depends_on:
        - rabbitmq
      environment:
        RABBITMQ_HOST: rabbitmq
      volumes:
        - ./dataAnalyzer:/analyzer
      networks:
        - MyNetwork  

networks:
  MyNetwork:
