version: '3'

services:
  rabbitmq:
    image: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
  
  generation:
    build: 
      context: ./DataGeneration
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./DataGeneration:/weatherProject
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq

  generation-celery:
    build:
      context: ./DataGeneration
    command: celery -A generation worker --loglevel=info
    volumes:
      - ./DataGeneration:/weatherProject
    depends_on:
      - rabbitmq
