version: '3'
services:
  rabbitmq:
    image: "rabbitmq:3.10-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - my_network
    environment:
      RABBITMQ_ERLANG_COOKIE: "A_secure_cookie_with_20_chars"

  generator:
    build:
      context: ./dataGenerator/
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_HOST: rabbitmq
    volumes:
      - ./dataGenerator:/generation
    networks:
      - my_network
  
  webservice:
    build:
      context: ./webservice/ 
    depends_on:
      - mongodb
    volumes:
      - ./webservice:/webservice    
    networks:
      - my_network
    ports:
      - "8000:8000" 
    environment:
      MONGO_URI: mongodb://mongodb:27017

  analyzer:
    build:
      context: ./dataAnalyzer/
    depends_on:
      - rabbitmq
      - mongodb
    environment:
      RABBITMQ_HOST: rabbitmq
      MONGO_URI: mongodb://mongodb:27017
      REDIS_HOST: redis
    volumes:
      - ./dataAnalyzer:/analyzer
    networks:
      - my_network

  mongodb:
    image: "mongo:latest"
    ports:
      - "27017:27017"
    networks:
      - my_network
    volumes:
      - mongo-data:/data/db
  
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    networks:
      - my_network
    volumes:
      - redis-data:/data/db

volumes:
  mongo-data:
  redis-data:

networks:
  my_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/16
